API_KEY: "AQEwhmfxLYvPbBVDw0m\/n3Q5qf3VfI5eGbBFVXVXyGH6zDVJmQ80Fa6axpQwFPD\/pPFqEMFdWw2+5HzctViMSCJMYAc=-ZDEniCmf3ap6AyBPXDHZ4UFNVdVLXG3C1orz10ZYuTk=-Tg^$zK4Q$5@ZS[R,"
MERCHANT_ACCOUNT: "TestMerchantAccount"
CLIENT_KEY: "test_7XPKZSBB4JCNXKUMGTPBFCEQC4IH3VSD"