PORT: "8080"
HMAC_KEY: "0DAF8E76B2868C4EC2769CF623C58E70C3C60FC81C5EA420CCA5E7C572023EF6"
API_KEY: "AQEwhmfxLYvPbBVDw0m\/n3Q5qf3VfI5eGbBFVXVXyGH6zDVJmQ80Fa6axpQwFPD\/pPFqEMFdWw2+5HzctViMSCJMYAc=-ZDEniCmf3ap6AyBPXDHZ4UFNVdVLXG3C1orz10ZYuTk=-Tg^$zK4Q$5@ZS[R,"
MERCHANT_ACCOUNT: "TestMerchantAccount"
CLIENT_KEY: "test_7XPKZSBB4JCNXKUMGTPBFCEQC4IH3VSD"